### ISSUE TITLE
expose report path through maven plugin

### ISSUE THREAD

**Issue by MykolaGolubyev** [testingisdocumenting/webtau#459] opened 2019-11-25 02:10 UTC
Config values are defined in: `com.twosigma.webtau.cfg.WebTauConfig`
Maven plugin entry point: `com.twosigma.webtau.maven.WebTauMavenRun`
Config key to expose: `reportPath`

**Comment by tsiq-karold** [comment] 2019-11-25 09:46
Might be a good idea to find a way to convert any plugin config into webtau cfg so we don't have to keep adding fields to `WebTauMavenRun` (or the other one whose name escapes me).

**Comment by MykolaGolubyev** [comment] 2019-11-25 16:37
Would be nice for sure. From what I know about maven plugins is that you need to declare each field so xml validation take place. Or do you suggest to pass like a blob or something?

**Comment by tsiq-karold** [comment] 2019-11-25 16:56
Not an expert on Maven plugins by any means but I think there is a way to just have a configuration node and get a hold of all child nodes.  I don't know what it is though.

**Comment by oneemo95** [comment] 2021-09-29 23:52
Duplicate of #174 
Duplicate of #125 
Duplicate of #135 
Duplicate of #945 
Duplicate of #777

**Comment by MykolaGolubyev** [comment] 2021-09-30 01:08
@oneemo95 what is going on?

**Closed** 2022-06-14 15:43 UTC
Labels: good first issue
