### ISSUE TITLE
Implement equals and compareTo on DataNode

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#227] opened 2018-12-12 13:07 UTC
This will allow things like:
```
if (foo.bar == "blah")
```
on responses for example.

**Comment by MykolaGolubyev** [comment] 2018-12-15 23:55
This turned out to be tricky in Groovy :(
if it is only `==` then no issues, but for symmetry we may need to support `foo.bar > 10` and this leads to complications
https://stackoverflow.com/questions/53798075/groovy-compareto-for-customclass-and-numbers-strings

**Comment by MykolaGolubyev** [comment] 2019-02-04 00:31
@tsiq-karold any ideas? we added `.get()` so not that much typing, the issue is there is no compile time warning. Wonder if some sort of AST should come to the rescue. I.e. detect that value inside if is an actual DataNode (at compile time) and automatically add .get() to it?

**Comment by tsiq-karold** [comment] 2019-02-04 09:43
We could do the AST trick, not sure it's necessarily worth the effort though.

**Comment by MykolaGolubyev** [comment] 2019-08-06 13:12
Groovy 2.5.7 changelog mentioned some fixes around the symmetry. Unfortunately I nuked the branch. Will try again. 
https://issues.apache.org/jira/browse/GROOVY-7954

**Comment by MykolaGolubyev** [comment] 2019-08-07 14:32
There is still an issue with handling `==` comparison of objects that don't implement `Comparable` (e.g. arrays).

**Comment by MykolaGolubyev** [comment] 2021-05-23 02:16
closing this for now as not much else can be done

**Closed by MykolaGolubyev** 2021-05-23 02:16 UTC
